- name: install ngninx
  yum:
    name: nginx
    
- name: Generate DH Parameters with a different size (2048 bits)
  openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 2048

- name: Copy SSL CRT certificate hosts
  copy:
    src: "{{ MINIO_S3HOST }}.crt"
    dest: "/etc/ssl/{{ MINIO_S3HOST }}.crt"
    mode: "0664"
    owner: "root"
    group: "root"
  when: (MINIO_S3HOST is defined)

- name: Copy SSL KEY certificate hosts
  copy:
    src: "{{ MINIO_S3HOST }}.key"
    dest: "/etc/ssl/{{ MINIO_S3HOST }}.key"
    mode: "0664"
    owner: "root"
    group: "root"
  when: (MINIO_S3HOST is defined)

- name: Template configuration file for /etc/nginx/nginx.conf
  template:
    src:  nginx.conf.j2
    dest: '/etc/nginx/nginx.conf'
  notify:
    - restart nginx
  tags: reconfigure

- name: Open ports for nginx
  firewalld:
    port: "80/tcp"
    permanent: yes
    state: enabled
    immediate: yes

- name: Open ports for nginx
  firewalld:
    port: "9000/tcp"
    permanent: yes
    state: enabled
    immediate: yes

- name: Open ports for nginx
  firewalld:
    port: "443/tcp"
    permanent: yes
    state: enabled
    immediate: yes

- name: enable and start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes