---
- name: Create minio directory
  file:
    state: directory
    owner: "{{ dockerminio_user }}"
    group: "{{ dockerminio_user }}"
    mode: 0755
    dest: /home/{{ dockerminio_user }}/minio

- name: Copy docker-compose.yml
  template:
    src: 'docker-compose.yml.j2'
    dest: '/home/{{ dockerminio_user }}/minio/docker-compose.yml'
    owner: "{{ dockerminio_user }}"
    group: "{{ dockerminio_user }}"
    mode: '0755'
  ignore_errors: true

- name: Start Docker Minio container
  command: "{{ docker_compose_path }} up -d"
  become: yes
  become_user: "{{ dockerminio_user }}"
  args:
    chdir: "/home/{{ dockerminio_user }}/minio/"
  ignore_errors: true

